// Package vm boots a single-use microVM through flintlock and talks to it over SSH.
package vm

import (
	"bufio"
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"golang.org/x/crypto/ssh"
	"gopkg.in/yaml.v3"

	"github.com/liquidmetal-dev/flintlock/api/types"

	"github.com/ismoilovdevml/firerunner/internal/config"
	"github.com/ismoilovdevml/firerunner/internal/flintlock"
)

// Instance is a booted microVM.
type Instance struct {
	ID  string `json:"id"`
	UID string `json:"uid"`
	IP  string `json:"ip"`
	// HostKey is the microVM's SSH host public key ("ssh-ed25519 AAAA..."),
	// generated by the host and injected at boot. Every SSH connection pins
	// it, so another guest that takes over this VM's IP cannot receive the job.
	HostKey string `json:"host_key,omitempty"`
}

// KnownHostsDir holds one pinned known_hosts file per microVM.
var KnownHostsDir = "/run/firerunner/known_hosts"

// HostKey is a per-VM SSH host key pair in OpenSSH formats.
type HostKey struct {
	Private string
	Public  string
}

// NewHostKey generates an ed25519 SSH host key for one microVM.
func NewHostKey() (HostKey, error) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return HostKey{}, err
	}
	block, err := ssh.MarshalPrivateKey(priv, "")
	if err != nil {
		return HostKey{}, err
	}
	sshPub, err := ssh.NewPublicKey(pub)
	if err != nil {
		return HostKey{}, err
	}
	return HostKey{
		Private: string(pem.EncodeToMemory(block)),
		Public:  strings.TrimSpace(string(ssh.MarshalAuthorizedKey(sshPub))),
	}, nil
}

// Boot creates the microVM and waits until it answers on SSH.
// On failure the microVM is deleted before returning.
func Boot(ctx context.Context, cfg config.Config, fl *flintlock.Client, id string, labels map[string]string) (*Instance, error) {
	pub, err := os.ReadFile(cfg.Network.SSHKey + ".pub")
	if err != nil {
		return nil, fmt.Errorf("reading SSH public key: %w", err)
	}
	hostKey, err := NewHostKey()
	if err != nil {
		return nil, fmt.Errorf("generating host key: %w", err)
	}
	mac := MAC(id)
	uid, err := fl.Create(ctx, Spec(cfg, id, mac, strings.TrimSpace(string(pub)), hostKey, labels))
	if err != nil {
		return nil, fmt.Errorf("creating microVM %s: %w", id, err)
	}
	inst := &Instance{ID: id, UID: uid, HostKey: hostKey.Public}

	fail := func(err error) (*Instance, error) {
		dctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		_ = fl.Delete(dctx, uid)
		Forget(cfg, id)
		return nil, err
	}

	deadline := time.Now().Add(cfg.VM.BootTimeout)
	for inst.IP == "" {
		if time.Now().After(deadline) {
			return fail(fmt.Errorf("microVM %s got no DHCP lease within %s (see: firerunner vm logs %s)", id, cfg.VM.BootTimeout, id))
		}
		if inst.IP, err = LeaseIP(cfg.Network.LeasesFile, mac); err != nil {
			return fail(err)
		}
		if inst.IP == "" {
			if err := sleep(ctx, time.Second); err != nil {
				return fail(err)
			}
		}
	}
	for SSH(cfg, inst, "true").Run() != nil {
		if time.Now().After(deadline) {
			return fail(fmt.Errorf("microVM %s at %s did not answer SSH within %s", id, inst.IP, cfg.VM.BootTimeout))
		}
		if err := sleep(ctx, time.Second); err != nil {
			return fail(err)
		}
	}
	return inst, nil
}

// Spec builds the flintlock request for a job microVM. cloud-init documents
// are marshalled, never formatted, so no value can inject YAML keys.
func Spec(cfg config.Config, id, mac, sshPubKey string, hostKey HostKey, labels map[string]string) *types.MicroVMSpec {
	daemonJSON, _ := json.Marshal(DockerDaemonConfig(cfg))
	ud, _ := yaml.Marshal(map[string]any{
		"hostname":     id,
		"disable_root": false,
		"users":        []map[string]any{{"name": "root", "ssh_authorized_keys": []string{sshPubKey}}},
		"bootcmd":      []string{"ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf"},
		// The host pins this key; other key types are not generated.
		"ssh_deletekeys":  true,
		"ssh_genkeytypes": []string{},
		"ssh_keys":        map[string]string{"ed25519_private": hostKey.Private, "ed25519_public": hostKey.Public},
		"write_files":     []map[string]string{{"path": "/etc/docker/daemon.json", "content": string(daemonJSON)}},
	})
	userData := "#cloud-config\n" + string(ud)
	md, _ := yaml.Marshal(map[string]string{
		"instance_id":    cfg.Flintlock.Namespace + "/" + id,
		"local_hostname": id,
		"platform":       "liquid_metal",
	})
	metaData := string(md)

	kernelFile := "boot/vmlinux"
	rootfs := cfg.VM.RootFSImage
	cmdline := map[string]string{}
	for k, v := range cfg.VM.KernelCmdline {
		cmdline[k] = v
	}
	return &types.MicroVMSpec{
		Id:         id,
		Labels:     labels,
		Vcpu:       int32(cfg.VM.VCPU),
		MemoryInMb: int32(cfg.VM.MemoryMB),
		Kernel: &types.Kernel{
			Image:            cfg.VM.KernelImage,
			Filename:         &kernelFile,
			Cmdline:          cmdline,
			AddNetworkConfig: true,
		},
		RootVolume: &types.Volume{
			Id:     "root",
			Source: &types.VolumeSource{ContainerSource: &rootfs},
		},
		Interfaces: []*types.NetworkInterface{{
			DeviceId: "eth1",
			Type:     types.NetworkInterface_TAP,
			GuestMac: &mac,
		}},
		Metadata: map[string]string{
			"meta-data": base64.StdEncoding.EncodeToString([]byte(metaData)),
			"user-data": base64.StdEncoding.EncodeToString([]byte(userData)),
			// Without vendor-data cloud-init retries the metadata service ~10s per boot.
			"vendor-data": base64.StdEncoding.EncodeToString([]byte("#cloud-config\n{}\n")),
		},
	}
}

// DockerDaemonConfig is the guest's /etc/docker/daemon.json.
func DockerDaemonConfig(cfg config.Config) map[string]any {
	d := map[string]any{
		"bip":                   cfg.VM.DockerBIP,
		"default-address-pools": []map[string]any{{"base": cfg.VM.DockerAddressPool, "size": 24}},
	}
	if cfg.VM.RegistryMirror != "" {
		d["registry-mirrors"] = []string{cfg.VM.RegistryMirror}
	}
	return d
}

// MAC derives a stable, locally administered MAC from the microVM id,
// so its DHCP lease can be found without asking the guest.
func MAC(id string) string {
	h := sha256.Sum256([]byte(id))
	return fmt.Sprintf("aa:fc:%02x:%02x:%02x:%02x", h[0], h[1], h[2], h[3])
}

// LeaseIP returns the address dnsmasq leased to mac, or "" if there is none yet.
func LeaseIP(leasesFile, mac string) (string, error) {
	l, err := findLease(leasesFile, mac)
	if l == nil {
		return "", err
	}
	return l.ip, err
}

type lease struct{ mac, ip, clientID string }

func findLease(leasesFile, mac string) (*lease, error) {
	f, err := os.Open(leasesFile)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	defer f.Close()
	var found *lease
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		// <expiry> <mac> <ip> <hostname> <client-id>
		fields := strings.Fields(sc.Text())
		if len(fields) >= 3 && strings.EqualFold(fields[1], mac) {
			found = &lease{mac: fields[1], ip: fields[2]}
			if len(fields) >= 5 && fields[4] != "*" {
				found.clientID = fields[4]
			}
		}
	}
	return found, sc.Err()
}

// Forget drops what the host keeps about a deleted microVM: its pinned host
// key and its DHCP lease. Releasing the lease frees the address at once;
// without it every VM holds an address until the lease expires.
func Forget(cfg config.Config, id string) {
	RemoveKnownHosts(id)
	l, err := findLease(cfg.Network.LeasesFile, MAC(id))
	if err != nil || l == nil {
		return
	}
	dev := routeDev(l.ip)
	if dev == "" {
		return
	}
	args := []string{dev, l.ip, l.mac}
	if l.clientID != "" {
		args = append(args, l.clientID)
	}
	_ = releaseLease(args...) // dnsmasq-utils missing: the lease just expires
}

// releaseLease and routeDev are variables so tests need no dnsmasq.
var releaseLease = func(args ...string) error { return exec.Command("dhcp_release", args...).Run() }

var routeDev = func(ip string) string {
	out, err := exec.Command("ip", "-o", "route", "get", ip).Output()
	if err != nil {
		return ""
	}
	f := strings.Fields(string(out))
	for i := 0; i+1 < len(f); i++ {
		if f[i] == "dev" {
			return f[i+1]
		}
	}
	return ""
}

// SSH returns a command that runs args in the microVM as root. The VM's
// host key is pinned under its id (HostKeyAlias), so the connection fails
// if anything else answers on the VM's IP.
func SSH(cfg config.Config, inst *Instance, args ...string) *exec.Cmd {
	base := []string{"-q", "-i", cfg.Network.SSHKey, "-o", "LogLevel=ERROR", "-o", "ConnectTimeout=3", "-o", "ServerAliveInterval=15"}
	if file, err := knownHosts(inst); err == nil {
		base = append(base, "-o", "StrictHostKeyChecking=yes", "-o", "UserKnownHostsFile="+file, "-o", "HostKeyAlias="+inst.ID)
	} else {
		// Only VMs created before host-key pinning existed (no HostKey recorded).
		fmt.Fprintf(os.Stderr, "warning: %v; connecting to %s without host key verification\n", err, inst.ID)
		base = append(base, "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null")
	}
	base = append(base, "root@"+inst.IP)
	return exec.Command("ssh", append(base, args...)...)
}

func knownHosts(inst *Instance) (string, error) {
	if inst.HostKey == "" {
		return "", fmt.Errorf("no host key recorded for %s", inst.ID)
	}
	if err := os.MkdirAll(KnownHostsDir, 0o700); err != nil {
		return "", err
	}
	file := filepath.Join(KnownHostsDir, filepath.Base(inst.ID))
	return file, os.WriteFile(file, []byte(inst.ID+" "+inst.HostKey+"\n"), 0o600)
}

// RemoveKnownHosts deletes the pinned key file of a deleted microVM.
func RemoveKnownHosts(id string) { _ = os.Remove(filepath.Join(KnownHostsDir, filepath.Base(id))) }

// RunScript streams a shell script into the microVM and returns its exit code.
func RunScript(cfg config.Config, inst *Instance, script io.Reader, stdout, stderr io.Writer) (int, error) {
	cmd := SSH(cfg, inst, "/bin/bash")
	cmd.Stdin, cmd.Stdout, cmd.Stderr = script, stdout, stderr
	return ExitCode(cmd.Run())
}

// ExitCode turns the error of exec.Cmd.Run into an exit code; err is only
// returned when the command could not run at all.
func ExitCode(err error) (int, error) {
	var exitErr *exec.ExitError
	if errors.As(err, &exitErr) {
		return exitErr.ExitCode(), nil
	}
	if err != nil {
		return -1, err
	}
	return 0, nil
}

func sleep(ctx context.Context, d time.Duration) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-time.After(d):
		return nil
	}
}
